In [3]:
import numpy as np

In [4]:
class StateMachine:
    def __init__(self):
        self.handlers = {}
        self.startState = None
        self.endStates = []
        
        
    def add_state(self,name,handler,end_state = 0):
        name = name.upper()
        self.handlers[name] = handler
        if end_state:
            self.endStates.append(name)
            
    def set_start(self,name):
        self.startState = name.upper()
        
    def run(self,cargo):
        
        handler = self.handlers[self.startState]
  

        # 从Start状态开始进行处理
        while True:
            (newState,cargo) = handler(cargo)# 经过状态转移函数变换到新状态
            if newState.upper() in self.endStates:# 如果跳到终止状态,则打印状态并结束循环
                print("Reached",newState)
                break
            else: # 否则将转移函数切换为新状态下的转移函数 
                handler = self.handlers[newState.upper()]
            

        


In [8]:

def start_game(game_grid):
    game_grid[np.random.randint(4)][np.random.randint(4)] = np.random.randint(1,3)*2
    next_num = choose_next_position(game_grid)
    game_grid[next_num[0]][next_num[1]] = np.random.randint(1,3)*2
    newState = "Continue"        
    return (newState, game_grid)
    
def continue_game(game_grid):
    show_grid(game_grid)
    command = input("输入wasd控制移动方向，q退出游戏：")
    old_grid = game_grid
    list1 = ["W","A","S","D","Q"]
    if command.upper() in list1:
        game_grid = grid_shift(command, game_grid)#移动数字
    if (np.all(game_grid == 0)):
        newState = "End"
    elif (old_grid==game_grid).all():
        newState = "Continue"
    else:
        next_num = choose_next_position(game_grid)
        game_grid[next_num[0]][next_num[1]] = np.random.randint(1,3)*2#产生新数字
        if can_be_continue(game_grid):#判断是否游戏结束
            newState = "Continue"
        else:
            newState = "End"    
    return (newState, game_grid)
      

def choose_next_position(grid):
    zero_position = np.argwhere(grid == 0)
    return_index = np.random.randint(zero_position.shape[0])
    return zero_position[return_index]

#判断是否无路可走
def can_be_continue(grid):
    if (np.any(grid == 0)):       
        return True
    else:
        for i in range(4):
            if (grid[i][0]==grid[i][1]) or (grid[i][1]==grid[i][2]) or (grid[i][2]==grid[i][3]):
                return True
            if (grid[0][i]==grid[1][i]) or (grid[1][i]==grid[2][i]) or (grid[2][i]==grid[3][i]):
                return True
        else:
            return False

def up_move(grid):
    new_grid = np.zeros((4,4),dtype=int)
    for i in range(4):
        num_location = np.argwhere(grid[:,i] != 0)
        num_len = len(num_location)
        for j in range(num_len):
            new_grid[j][i] = grid[num_location[j][0]][i] 
        if (new_grid[3][i]==new_grid[2][i])and(new_grid[3][i] != 0):
            new_grid[2][i] = 2*new_grid[3][i]
            new_grid[3][i] = 0
        elif (new_grid[2][i]==new_grid[1][i])and(new_grid[2][i] != 0):
            new_grid[1][i] = 2*new_grid[2][i]
            new_grid[2][i] = new_grid[3][i]
            new_grid[3][i] = 0
        elif (new_grid[1][i]==new_grid[0][i])and(new_grid[1][i] != 0):
            new_grid[0][i] = 2*new_grid[1][i]
            new_grid[1][i] = new_grid[2][i]
            new_grid[2][i] = new_grid[3][i]
            new_grid[3][i] = 0
    return new_grid

def left_move(grid):
    new_grid = np.zeros((4,4),dtype=int)
    for i in range(4):
        num_location = np.argwhere(grid[i] != 0)
        num_len = len(num_location)
        for j in range(num_len):
            new_grid[i][j] = grid[i][num_location[j][0]]
        if (new_grid[i][3]==new_grid[i][2])and(new_grid[i][3] != 0):
            new_grid[i][2] = 2*new_grid[i][3]
            new_grid[i][3] = 0
        elif (new_grid[i][2]==new_grid[i][1])and(new_grid[i][2] != 0):
            new_grid[i][1] = 2*new_grid[i][2]
            new_grid[i][2] = new_grid[i][3] 
            new_grid[i][3] = 0
        elif (new_grid[i][1]==new_grid[i][0])and(new_grid[i][1] != 0):
            new_grid[i][0] = 2*new_grid[i][1]   
            new_grid[i][1] = new_grid[i][2]
            new_grid[i][2] = new_grid[i][3]
            new_grid[i][3] = 0
    return new_grid

def down_move(grid):
    new_grid = np.zeros((4,4),dtype=int)
    for i in range(4):
        num_location = np.argwhere(grid[:,i] != 0)
        num_len = len(num_location)
        for j in range(num_len):
            new_grid[3-j][i] = grid[num_location[num_len-j-1][0]][i]
        if (new_grid[0][i]==new_grid[1][i])and(new_grid[0][i] != 0):
            new_grid[1][i] = 2*new_grid[0][i]
            new_grid[0][i] = 0
        elif (new_grid[1][i]==new_grid[2][i])and(new_grid[1][i] != 0):
            new_grid[2][i] = 2*new_grid[1][i]
            new_grid[1][i] = new_grid[0][i]
            new_grid[0][i] = 0
            
        elif (new_grid[2][i]==new_grid[3][i])and(new_grid[2][i] != 0):
            new_grid[3][i] = 2*new_grid[2][i]
            new_grid[2][i] = new_grid[1][i]
            new_grid[1][i] = new_grid[0][i]
            new_grid[0][i] = 0
    return new_grid    

def right_move(grid):
    new_grid = np.zeros((4,4),dtype=int)
    for i in range(4):
        num_location = np.argwhere(grid[i] != 0)
        num_len = len(num_location)
        for j in range(num_len):
            new_grid[i][3-j] = grid[i][num_location[num_len-j-1][0]]
        if (new_grid[i][0]==new_grid[i][1])and(new_grid[i][0] != 0):
            new_grid[i][1] = 2*new_grid[i][0]
            new_grid[i][0] = 0
        elif (new_grid[i][1]==new_grid[i][2])and(new_grid[i][1] != 0):
            new_grid[i][2] = 2*new_grid[i][1]
            new_grid[i][1] = new_grid[i][0]
            new_grid[i][0] = 0
            
        elif (new_grid[i][2]==new_grid[i][3])and(new_grid[i][2] != 0):
            new_grid[i][3] = 2*new_grid[i][2]
            new_grid[i][2] = new_grid[i][1]
            new_grid[i][1] = new_grid[i][0]
            new_grid[i][0] = 0
    return new_grid    

def quit_game(grid):   
    return np.zeros((4,4),dtype=int)
    
#运动指令对应的操作        
def grid_shift(command,grid):
    command_list = {"W":up_move,"A":left_move,"S":down_move,"D":right_move,"Q":quit_game}
    if command.upper() in command_list:
        shift_result = command_list[command.upper()](grid)
    return shift_result
        
    
    
def show_grid(grid):
    print("——————————————————————————————————————————————————————————————————————————————————————————————————————")
    str_temp = ""
    print(" ==================== ")
    for i in range(4):
        print("||                  ||")
        print("||",end='')
        for j in range(4):
            if grid[i][j] == 0:
                print("%4s"%str_temp,end="")
            else:
                print("%4d"%grid[i][j],end ="")
        print("  ||")
    print("||                  ||")
    print(" ==================== ")
                    
                  
            
    
if __name__== "__main__":
    m = StateMachine()
    m.add_state("Start",start_game)#添加游戏开始状态
    m.add_state("Continue",continue_game)#添加游戏进行状态
    m.add_state("End",None, end_state=1)#添加游戏结束状态
    
    start_grid = np.zeros((4,4),dtype=int)
    m.set_start("Start")
    m.run(start_grid)

——————————————————————————————————————————————————————————————————————————————————————————————————————
||                  ||
||                  ||
||                  ||
||   4              ||
||                  ||
||   4              ||
||                  ||
||                  ||
||                  ||
输入wasd控制移动方向，q退出游戏：q
Reached End


False


False

[[ 0  0  0  6]
 [ 1  2  4  6]
 [ 0  0  2  5]
 [ 5  2 65 32]]
||                  ||
||               6  ||
||                  ||
||   1   2   4   6  ||
||                  ||
||           2   5  ||
||                  ||
||   5   2  65  32  ||
||                  ||


False
